
openapi: 3.0.0
info:
  title: Real-Time Threat Intelligence API
  version: 1.0.0
  description: API for collecting, analyzing, and responding to cybersecurity threats

paths:
  /api/fetchShodanThreatData:
    post:
      summary: Fetch threat data from Shodan and store it in Supabase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ip:
                  type: string
                  example: "8.8.8.8"
      responses:
        '200':
          description: Data fetched and stored successfully
        '400':
          description: IP address is required
        '500':
          description: Error during fetch or storage

  /api/getThreatData:
    get:
      summary: Get all threat data for dashboard display
      responses:
        '200':
          description: List of threats from TVA mapping

  /api/getHighRiskThreats:
    get:
      summary: Get only high-risk threats (risk score > 15)
      responses:
        '200':
          description: List of high-risk threat mappings

  /api/getRecentAlerts:
    get:
      summary: Retrieve 10 most recent alerts
      responses:
        '200':
          description: List of alert records

  /api/updateAlertStatus:
    post:
      summary: Update the status of an alert
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: "1234"
                status:
                  type: string
                  example: "resolved"
      responses:
        '200':
          description: Alert status updated

  /api/performCBA:
    post:
      summary: Perform cost-benefit analysis on a threat scenario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                threatId:
                  type: string
                threatType:
                  type: string
                  example: "SQL Injection"
                assetValue:
                  type: number
                  example: 10000
                controls:
                  type: array
                  items:
                    type: object
      responses:
        '200':
          description: CBA results

  /api/cbaHistory:
    get:
      summary: Retrieve all past cost-benefit analyses
      responses:
        '200':
          description: CBA history

  /api/incidentResponse:
    get:
      summary: Get incident response plan based on threat type
      parameters:
        - in: query
          name: threatType
          schema:
            type: string
          required: true
          example: "Phishing"
      responses:
        '200':
          description: Suggested incident response plan

  /api/predictThreatBehavior:
    post:
      summary: Get AI-predicted next step for a threat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  example: "SQL Injection detected on login page"
      responses:
        '200':
          description: Prediction generated by local AI model

  /shodan:
    get:
      summary: Fetch and store Shodan data for a single IP
      parameters:
        - in: query
          name: ip
          schema:
            type: string
          required: true
          example: "8.8.8.8"
      responses:
        '200':
          description: Shodan threat data stored

  /shodan/scan:
    post:
      summary: Perform Shodan scans for multiple IPs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ips:
                  type: array
                  items:
                    type: string
                  example: ["8.8.8.8", "1.1.1.1"]
      responses:
        '200':
          description: Shodan results for all IPs
